export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './layout.scss'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className='main-layout'>
          <nav>
            Navbar
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
